package com.erp.lead.model.impl;

import com.erp.lead.model.FieldEntry;
import com.erp.lead.model.FieldEntryModel;
import com.erp.lead.model.FieldEntrySoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;
import java.lang.reflect.Proxy;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the FieldEntry service. Represents a row in the &quot;field_entries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.erp.lead.model.FieldEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FieldEntryImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a Field Entry model instance should use the {@link com.erp.lead.model.FieldEntry} interface instead.
 * </p>
 *
 * @author Thangaperumal
 * @see FieldEntryImpl
 * @see com.erp.lead.model.FieldEntry
 * @see com.erp.lead.model.FieldEntryModel
 * @generated
 */
public class FieldEntryModelImpl extends BaseModelImpl<FieldEntry>
    implements FieldEntryModel {
    public static final String TABLE_NAME = "field_entries";
    public static final Object[][] TABLE_COLUMNS = {
            { "id", new Integer(Types.INTEGER) },
            { "form_entry_id", new Integer(Types.INTEGER) },
            { "name", new Integer(Types.VARCHAR) },
            { "value", new Integer(Types.VARCHAR) }
        };
    public static final String TABLE_SQL_CREATE = "create table field_entries (id INTEGER not null primary key IDENTITY,form_entry_id INTEGER,name VARCHAR(75) null,value VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table field_entries";
    public static final String DATA_SOURCE = "cisDS";
    public static final String SESSION_FACTORY = "cisSessionFactory";
    public static final String TX_MANAGER = "cisTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.rosettastone.cis.model.FieldEntry"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.rosettastone.cis.model.FieldEntry"),
            true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.rosettastone.cis.model.FieldEntry"));
    private int _id;
    private int _formEntryId;
    private String _name;
    private String _value;

    public FieldEntryModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static FieldEntry toModel(FieldEntrySoap soapModel) {
        FieldEntry model = new FieldEntryImpl();

        model.setId(soapModel.getId());
        model.setFormEntryId(soapModel.getFormEntryId());
        model.setName(soapModel.getName());
        model.setValue(soapModel.getValue());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<FieldEntry> toModels(FieldEntrySoap[] soapModels) {
        List<FieldEntry> models = new ArrayList<FieldEntry>(soapModels.length);

        for (FieldEntrySoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public int getPrimaryKey() {
        return _id;
    }

    public void setPrimaryKey(int pk) {
        setId(pk);
    }

    public Serializable getPrimaryKeyObj() {
        return new Integer(_id);
    }

    public int getId() {
        return _id;
    }

    public void setId(int id) {
        _id = id;
    }

    public int getFormEntryId() {
        return _formEntryId;
    }

    public void setFormEntryId(int formEntryId) {
        _formEntryId = formEntryId;
    }

    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    public void setName(String name) {
        _name = name;
    }

    public String getValue() {
        if (_value == null) {
            return StringPool.BLANK;
        } else {
            return _value;
        }
    }

    public void setValue(String value) {
        _value = value;
    }

    public FieldEntry toEscapedModel() {
        if (isEscapedModel()) {
            return (FieldEntry) this;
        } else {
            return (FieldEntry) Proxy.newProxyInstance(FieldEntry.class.getClassLoader(),
                new Class[] { FieldEntry.class },
                new AutoEscapeBeanHandler(this));
        }
    }

    public Object clone() {
        FieldEntryImpl fieldEntryImpl = new FieldEntryImpl();

        fieldEntryImpl.setId(getId());

        fieldEntryImpl.setFormEntryId(getFormEntryId());

        fieldEntryImpl.setName(getName());

        fieldEntryImpl.setValue(getValue());

        return fieldEntryImpl;
    }

    public int compareTo(FieldEntry fieldEntry) {
        int pk = fieldEntry.getPrimaryKey();

        if (getPrimaryKey() < pk) {
            return -1;
        } else if (getPrimaryKey() > pk) {
            return 1;
        } else {
            return 0;
        }
    }

    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        FieldEntry fieldEntry = null;

        try {
            fieldEntry = (FieldEntry) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        int pk = fieldEntry.getPrimaryKey();

        if (getPrimaryKey() == pk) {
            return true;
        } else {
            return false;
        }
    }

    public int hashCode() {
        return getPrimaryKey();
    }

    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", formEntryId=");
        sb.append(getFormEntryId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", value=");
        sb.append(getValue());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("com.erp.lead.model.FieldEntry");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>formEntryId</column-name><column-value><![CDATA[");
        sb.append(getFormEntryId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>value</column-name><column-value><![CDATA[");
        sb.append(getValue());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
