package com.erp.lead.service.base;

import com.erp.lead.service.AddressLocalService;
import com.erp.lead.service.AddressService;
import com.erp.lead.service.CountryLocalService;
import com.erp.lead.service.CountryService;
import com.erp.lead.service.CustomerLocalService;
import com.erp.lead.service.CustomerService;
import com.erp.lead.service.DemoItemLocalService;
import com.erp.lead.service.DemoItemService;
import com.erp.lead.service.EcOrderIdSequenceLocalService;
import com.erp.lead.service.EcOrderIdSequenceService;
import com.erp.lead.service.FieldEntryLocalService;
import com.erp.lead.service.FieldEntryService;
import com.erp.lead.service.FormEmailTemplateLocalService;
import com.erp.lead.service.FormEmailTemplateService;
import com.erp.lead.service.FormEntryLocalService;
import com.erp.lead.service.FormEntryService;
import com.erp.lead.service.FormExportLogLocalService;
import com.erp.lead.service.FormExportLogService;
import com.erp.lead.service.FormLocalService;
import com.erp.lead.service.FormService;
import com.erp.lead.service.LocalizationLocalService;
import com.erp.lead.service.LocalizationService;
import com.erp.lead.service.OrderLineLocalService;
import com.erp.lead.service.OrderLineService;
import com.erp.lead.service.OrderLocalService;
import com.erp.lead.service.OrderService;
import com.erp.lead.service.PromoLocalService;
import com.erp.lead.service.PromoService;
import com.erp.lead.service.SiteLocalService;
import com.erp.lead.service.SiteService;
import com.erp.lead.service.VerticalLocalService;
import com.erp.lead.service.VerticalService;
import com.erp.lead.service.persistence.AddressPersistence;
import com.erp.lead.service.persistence.CountryPersistence;
import com.erp.lead.service.persistence.CustomerPersistence;
import com.erp.lead.service.persistence.DemoItemPersistence;
import com.erp.lead.service.persistence.EcOrderIdSequencePersistence;
import com.erp.lead.service.persistence.FieldEntryPersistence;
import com.erp.lead.service.persistence.FormEmailTemplatePersistence;
import com.erp.lead.service.persistence.FormEntryFinder;
import com.erp.lead.service.persistence.FormEntryPersistence;
import com.erp.lead.service.persistence.FormExportLogFinder;
import com.erp.lead.service.persistence.FormExportLogPersistence;
import com.erp.lead.service.persistence.FormFinder;
import com.erp.lead.service.persistence.FormPersistence;
import com.erp.lead.service.persistence.LocalizationPersistence;
import com.erp.lead.service.persistence.OrderLinePersistence;
import com.erp.lead.service.persistence.OrderPersistence;
import com.erp.lead.service.persistence.PromoPersistence;
import com.erp.lead.service.persistence.SiteFinder;
import com.erp.lead.service.persistence.SitePersistence;
import com.erp.lead.service.persistence.VerticalPersistence;
import com.liferay.counter.service.CounterLocalService;
import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.base.PrincipalBean;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the Address remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.erp.lead.service.impl.AddressServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.erp.lead.service.AddressServiceUtil} to access the Address remote service.
 * </p>
 *
 * @author Thangaperumal
 * @see com.erp.lead.service.impl.AddressServiceImpl
 * @see com.erp.lead.service.AddressServiceUtil
 * @generated
 */
public abstract class AddressServiceBaseImpl extends PrincipalBean
    implements AddressService {
    @BeanReference(type = FormLocalService.class)
    protected FormLocalService formLocalService;
    @BeanReference(type = FormService.class)
    protected FormService formService;
    @BeanReference(type = FormPersistence.class)
    protected FormPersistence formPersistence;
    @BeanReference(type = FormFinder.class)
    protected FormFinder formFinder;
    @BeanReference(type = FormEntryLocalService.class)
    protected FormEntryLocalService formEntryLocalService;
    @BeanReference(type = FormEntryService.class)
    protected FormEntryService formEntryService;
    @BeanReference(type = FormEntryPersistence.class)
    protected FormEntryPersistence formEntryPersistence;
    @BeanReference(type = FormEntryFinder.class)
    protected FormEntryFinder formEntryFinder;
    @BeanReference(type = FieldEntryLocalService.class)
    protected FieldEntryLocalService fieldEntryLocalService;
    @BeanReference(type = FieldEntryService.class)
    protected FieldEntryService fieldEntryService;
    @BeanReference(type = FieldEntryPersistence.class)
    protected FieldEntryPersistence fieldEntryPersistence;
    @BeanReference(type = FormExportLogLocalService.class)
    protected FormExportLogLocalService formExportLogLocalService;
    @BeanReference(type = FormExportLogService.class)
    protected FormExportLogService formExportLogService;
    @BeanReference(type = FormExportLogPersistence.class)
    protected FormExportLogPersistence formExportLogPersistence;
    @BeanReference(type = FormExportLogFinder.class)
    protected FormExportLogFinder formExportLogFinder;
    @BeanReference(type = FormEmailTemplateLocalService.class)
    protected FormEmailTemplateLocalService formEmailTemplateLocalService;
    @BeanReference(type = FormEmailTemplateService.class)
    protected FormEmailTemplateService formEmailTemplateService;
    @BeanReference(type = FormEmailTemplatePersistence.class)
    protected FormEmailTemplatePersistence formEmailTemplatePersistence;
    @BeanReference(type = SiteLocalService.class)
    protected SiteLocalService siteLocalService;
    @BeanReference(type = SiteService.class)
    protected SiteService siteService;
    @BeanReference(type = SitePersistence.class)
    protected SitePersistence sitePersistence;
    @BeanReference(type = SiteFinder.class)
    protected SiteFinder siteFinder;
    @BeanReference(type = OrderLocalService.class)
    protected OrderLocalService orderLocalService;
    @BeanReference(type = OrderService.class)
    protected OrderService orderService;
    @BeanReference(type = OrderPersistence.class)
    protected OrderPersistence orderPersistence;
    @BeanReference(type = AddressLocalService.class)
    protected AddressLocalService addressLocalService;
    @BeanReference(type = AddressService.class)
    protected AddressService addressService;
    @BeanReference(type = AddressPersistence.class)
    protected AddressPersistence addressPersistence;
    @BeanReference(type = CustomerLocalService.class)
    protected CustomerLocalService customerLocalService;
    @BeanReference(type = CustomerService.class)
    protected CustomerService customerService;
    @BeanReference(type = CustomerPersistence.class)
    protected CustomerPersistence customerPersistence;
    @BeanReference(type = OrderLineLocalService.class)
    protected OrderLineLocalService orderLineLocalService;
    @BeanReference(type = OrderLineService.class)
    protected OrderLineService orderLineService;
    @BeanReference(type = OrderLinePersistence.class)
    protected OrderLinePersistence orderLinePersistence;
    @BeanReference(type = PromoLocalService.class)
    protected PromoLocalService promoLocalService;
    @BeanReference(type = PromoService.class)
    protected PromoService promoService;
    @BeanReference(type = PromoPersistence.class)
    protected PromoPersistence promoPersistence;
    @BeanReference(type = VerticalLocalService.class)
    protected VerticalLocalService verticalLocalService;
    @BeanReference(type = VerticalService.class)
    protected VerticalService verticalService;
    @BeanReference(type = VerticalPersistence.class)
    protected VerticalPersistence verticalPersistence;
    @BeanReference(type = DemoItemLocalService.class)
    protected DemoItemLocalService demoItemLocalService;
    @BeanReference(type = DemoItemService.class)
    protected DemoItemService demoItemService;
    @BeanReference(type = DemoItemPersistence.class)
    protected DemoItemPersistence demoItemPersistence;
    @BeanReference(type = LocalizationLocalService.class)
    protected LocalizationLocalService localizationLocalService;
    @BeanReference(type = LocalizationService.class)
    protected LocalizationService localizationService;
    @BeanReference(type = LocalizationPersistence.class)
    protected LocalizationPersistence localizationPersistence;
    @BeanReference(type = CountryLocalService.class)
    protected CountryLocalService countryLocalService;
    @BeanReference(type = CountryService.class)
    protected CountryService countryService;
    @BeanReference(type = CountryPersistence.class)
    protected CountryPersistence countryPersistence;
    @BeanReference(type = EcOrderIdSequenceLocalService.class)
    protected EcOrderIdSequenceLocalService ecOrderIdSequenceLocalService;
    @BeanReference(type = EcOrderIdSequenceService.class)
    protected EcOrderIdSequenceService ecOrderIdSequenceService;
    @BeanReference(type = EcOrderIdSequencePersistence.class)
    protected EcOrderIdSequencePersistence ecOrderIdSequencePersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;

    /**
     * Gets the Form local service.
     *
     * @return the Form local service
     */
    public FormLocalService getFormLocalService() {
        return formLocalService;
    }

    /**
     * Sets the Form local service.
     *
     * @param formLocalService the Form local service
     */
    public void setFormLocalService(FormLocalService formLocalService) {
        this.formLocalService = formLocalService;
    }

    /**
     * Gets the Form remote service.
     *
     * @return the Form remote service
     */
    public FormService getFormService() {
        return formService;
    }

    /**
     * Sets the Form remote service.
     *
     * @param formService the Form remote service
     */
    public void setFormService(FormService formService) {
        this.formService = formService;
    }

    /**
     * Gets the Form persistence.
     *
     * @return the Form persistence
     */
    public FormPersistence getFormPersistence() {
        return formPersistence;
    }

    /**
     * Sets the Form persistence.
     *
     * @param formPersistence the Form persistence
     */
    public void setFormPersistence(FormPersistence formPersistence) {
        this.formPersistence = formPersistence;
    }

    /**
     * Gets the Form finder.
     *
     * @return the Form finder
     */
    public FormFinder getFormFinder() {
        return formFinder;
    }

    /**
     * Sets the Form finder.
     *
     * @param formFinder the Form finder
     */
    public void setFormFinder(FormFinder formFinder) {
        this.formFinder = formFinder;
    }

    /**
     * Gets the Form Entry local service.
     *
     * @return the Form Entry local service
     */
    public FormEntryLocalService getFormEntryLocalService() {
        return formEntryLocalService;
    }

    /**
     * Sets the Form Entry local service.
     *
     * @param formEntryLocalService the Form Entry local service
     */
    public void setFormEntryLocalService(
        FormEntryLocalService formEntryLocalService) {
        this.formEntryLocalService = formEntryLocalService;
    }

    /**
     * Gets the Form Entry remote service.
     *
     * @return the Form Entry remote service
     */
    public FormEntryService getFormEntryService() {
        return formEntryService;
    }

    /**
     * Sets the Form Entry remote service.
     *
     * @param formEntryService the Form Entry remote service
     */
    public void setFormEntryService(FormEntryService formEntryService) {
        this.formEntryService = formEntryService;
    }

    /**
     * Gets the Form Entry persistence.
     *
     * @return the Form Entry persistence
     */
    public FormEntryPersistence getFormEntryPersistence() {
        return formEntryPersistence;
    }

    /**
     * Sets the Form Entry persistence.
     *
     * @param formEntryPersistence the Form Entry persistence
     */
    public void setFormEntryPersistence(
        FormEntryPersistence formEntryPersistence) {
        this.formEntryPersistence = formEntryPersistence;
    }

    /**
     * Gets the Form Entry finder.
     *
     * @return the Form Entry finder
     */
    public FormEntryFinder getFormEntryFinder() {
        return formEntryFinder;
    }

    /**
     * Sets the Form Entry finder.
     *
     * @param formEntryFinder the Form Entry finder
     */
    public void setFormEntryFinder(FormEntryFinder formEntryFinder) {
        this.formEntryFinder = formEntryFinder;
    }

    /**
     * Gets the Field Entry local service.
     *
     * @return the Field Entry local service
     */
    public FieldEntryLocalService getFieldEntryLocalService() {
        return fieldEntryLocalService;
    }

    /**
     * Sets the Field Entry local service.
     *
     * @param fieldEntryLocalService the Field Entry local service
     */
    public void setFieldEntryLocalService(
        FieldEntryLocalService fieldEntryLocalService) {
        this.fieldEntryLocalService = fieldEntryLocalService;
    }

    /**
     * Gets the Field Entry remote service.
     *
     * @return the Field Entry remote service
     */
    public FieldEntryService getFieldEntryService() {
        return fieldEntryService;
    }

    /**
     * Sets the Field Entry remote service.
     *
     * @param fieldEntryService the Field Entry remote service
     */
    public void setFieldEntryService(FieldEntryService fieldEntryService) {
        this.fieldEntryService = fieldEntryService;
    }

    /**
     * Gets the Field Entry persistence.
     *
     * @return the Field Entry persistence
     */
    public FieldEntryPersistence getFieldEntryPersistence() {
        return fieldEntryPersistence;
    }

    /**
     * Sets the Field Entry persistence.
     *
     * @param fieldEntryPersistence the Field Entry persistence
     */
    public void setFieldEntryPersistence(
        FieldEntryPersistence fieldEntryPersistence) {
        this.fieldEntryPersistence = fieldEntryPersistence;
    }

    /**
     * Gets the Form Export Logs local service.
     *
     * @return the Form Export Logs local service
     */
    public FormExportLogLocalService getFormExportLogLocalService() {
        return formExportLogLocalService;
    }

    /**
     * Sets the Form Export Logs local service.
     *
     * @param formExportLogLocalService the Form Export Logs local service
     */
    public void setFormExportLogLocalService(
        FormExportLogLocalService formExportLogLocalService) {
        this.formExportLogLocalService = formExportLogLocalService;
    }

    /**
     * Gets the Form Export Logs remote service.
     *
     * @return the Form Export Logs remote service
     */
    public FormExportLogService getFormExportLogService() {
        return formExportLogService;
    }

    /**
     * Sets the Form Export Logs remote service.
     *
     * @param formExportLogService the Form Export Logs remote service
     */
    public void setFormExportLogService(
        FormExportLogService formExportLogService) {
        this.formExportLogService = formExportLogService;
    }

    /**
     * Gets the Form Export Logs persistence.
     *
     * @return the Form Export Logs persistence
     */
    public FormExportLogPersistence getFormExportLogPersistence() {
        return formExportLogPersistence;
    }

    /**
     * Sets the Form Export Logs persistence.
     *
     * @param formExportLogPersistence the Form Export Logs persistence
     */
    public void setFormExportLogPersistence(
        FormExportLogPersistence formExportLogPersistence) {
        this.formExportLogPersistence = formExportLogPersistence;
    }

    /**
     * Gets the Form Export Logs finder.
     *
     * @return the Form Export Logs finder
     */
    public FormExportLogFinder getFormExportLogFinder() {
        return formExportLogFinder;
    }

    /**
     * Sets the Form Export Logs finder.
     *
     * @param formExportLogFinder the Form Export Logs finder
     */
    public void setFormExportLogFinder(FormExportLogFinder formExportLogFinder) {
        this.formExportLogFinder = formExportLogFinder;
    }

    /**
     * Gets the Form Email Templates local service.
     *
     * @return the Form Email Templates local service
     */
    public FormEmailTemplateLocalService getFormEmailTemplateLocalService() {
        return formEmailTemplateLocalService;
    }

    /**
     * Sets the Form Email Templates local service.
     *
     * @param formEmailTemplateLocalService the Form Email Templates local service
     */
    public void setFormEmailTemplateLocalService(
        FormEmailTemplateLocalService formEmailTemplateLocalService) {
        this.formEmailTemplateLocalService = formEmailTemplateLocalService;
    }

    /**
     * Gets the Form Email Templates remote service.
     *
     * @return the Form Email Templates remote service
     */
    public FormEmailTemplateService getFormEmailTemplateService() {
        return formEmailTemplateService;
    }

    /**
     * Sets the Form Email Templates remote service.
     *
     * @param formEmailTemplateService the Form Email Templates remote service
     */
    public void setFormEmailTemplateService(
        FormEmailTemplateService formEmailTemplateService) {
        this.formEmailTemplateService = formEmailTemplateService;
    }

    /**
     * Gets the Form Email Templates persistence.
     *
     * @return the Form Email Templates persistence
     */
    public FormEmailTemplatePersistence getFormEmailTemplatePersistence() {
        return formEmailTemplatePersistence;
    }

    /**
     * Sets the Form Email Templates persistence.
     *
     * @param formEmailTemplatePersistence the Form Email Templates persistence
     */
    public void setFormEmailTemplatePersistence(
        FormEmailTemplatePersistence formEmailTemplatePersistence) {
        this.formEmailTemplatePersistence = formEmailTemplatePersistence;
    }

    /**
     * Gets the Site local service.
     *
     * @return the Site local service
     */
    public SiteLocalService getSiteLocalService() {
        return siteLocalService;
    }

    /**
     * Sets the Site local service.
     *
     * @param siteLocalService the Site local service
     */
    public void setSiteLocalService(SiteLocalService siteLocalService) {
        this.siteLocalService = siteLocalService;
    }

    /**
     * Gets the Site remote service.
     *
     * @return the Site remote service
     */
    public SiteService getSiteService() {
        return siteService;
    }

    /**
     * Sets the Site remote service.
     *
     * @param siteService the Site remote service
     */
    public void setSiteService(SiteService siteService) {
        this.siteService = siteService;
    }

    /**
     * Gets the Site persistence.
     *
     * @return the Site persistence
     */
    public SitePersistence getSitePersistence() {
        return sitePersistence;
    }

    /**
     * Sets the Site persistence.
     *
     * @param sitePersistence the Site persistence
     */
    public void setSitePersistence(SitePersistence sitePersistence) {
        this.sitePersistence = sitePersistence;
    }

    /**
     * Gets the Site finder.
     *
     * @return the Site finder
     */
    public SiteFinder getSiteFinder() {
        return siteFinder;
    }

    /**
     * Sets the Site finder.
     *
     * @param siteFinder the Site finder
     */
    public void setSiteFinder(SiteFinder siteFinder) {
        this.siteFinder = siteFinder;
    }

    /**
     * Gets the Order local service.
     *
     * @return the Order local service
     */
    public OrderLocalService getOrderLocalService() {
        return orderLocalService;
    }

    /**
     * Sets the Order local service.
     *
     * @param orderLocalService the Order local service
     */
    public void setOrderLocalService(OrderLocalService orderLocalService) {
        this.orderLocalService = orderLocalService;
    }

    /**
     * Gets the Order remote service.
     *
     * @return the Order remote service
     */
    public OrderService getOrderService() {
        return orderService;
    }

    /**
     * Sets the Order remote service.
     *
     * @param orderService the Order remote service
     */
    public void setOrderService(OrderService orderService) {
        this.orderService = orderService;
    }

    /**
     * Gets the Order persistence.
     *
     * @return the Order persistence
     */
    public OrderPersistence getOrderPersistence() {
        return orderPersistence;
    }

    /**
     * Sets the Order persistence.
     *
     * @param orderPersistence the Order persistence
     */
    public void setOrderPersistence(OrderPersistence orderPersistence) {
        this.orderPersistence = orderPersistence;
    }

    /**
     * Gets the Address local service.
     *
     * @return the Address local service
     */
    public AddressLocalService getAddressLocalService() {
        return addressLocalService;
    }

    /**
     * Sets the Address local service.
     *
     * @param addressLocalService the Address local service
     */
    public void setAddressLocalService(AddressLocalService addressLocalService) {
        this.addressLocalService = addressLocalService;
    }

    /**
     * Gets the Address remote service.
     *
     * @return the Address remote service
     */
    public AddressService getAddressService() {
        return addressService;
    }

    /**
     * Sets the Address remote service.
     *
     * @param addressService the Address remote service
     */
    public void setAddressService(AddressService addressService) {
        this.addressService = addressService;
    }

    /**
     * Gets the Address persistence.
     *
     * @return the Address persistence
     */
    public AddressPersistence getAddressPersistence() {
        return addressPersistence;
    }

    /**
     * Sets the Address persistence.
     *
     * @param addressPersistence the Address persistence
     */
    public void setAddressPersistence(AddressPersistence addressPersistence) {
        this.addressPersistence = addressPersistence;
    }

    /**
     * Gets the Customer local service.
     *
     * @return the Customer local service
     */
    public CustomerLocalService getCustomerLocalService() {
        return customerLocalService;
    }

    /**
     * Sets the Customer local service.
     *
     * @param customerLocalService the Customer local service
     */
    public void setCustomerLocalService(
        CustomerLocalService customerLocalService) {
        this.customerLocalService = customerLocalService;
    }

    /**
     * Gets the Customer remote service.
     *
     * @return the Customer remote service
     */
    public CustomerService getCustomerService() {
        return customerService;
    }

    /**
     * Sets the Customer remote service.
     *
     * @param customerService the Customer remote service
     */
    public void setCustomerService(CustomerService customerService) {
        this.customerService = customerService;
    }

    /**
     * Gets the Customer persistence.
     *
     * @return the Customer persistence
     */
    public CustomerPersistence getCustomerPersistence() {
        return customerPersistence;
    }

    /**
     * Sets the Customer persistence.
     *
     * @param customerPersistence the Customer persistence
     */
    public void setCustomerPersistence(CustomerPersistence customerPersistence) {
        this.customerPersistence = customerPersistence;
    }

    /**
     * Gets the OrderLine local service.
     *
     * @return the OrderLine local service
     */
    public OrderLineLocalService getOrderLineLocalService() {
        return orderLineLocalService;
    }

    /**
     * Sets the OrderLine local service.
     *
     * @param orderLineLocalService the OrderLine local service
     */
    public void setOrderLineLocalService(
        OrderLineLocalService orderLineLocalService) {
        this.orderLineLocalService = orderLineLocalService;
    }

    /**
     * Gets the OrderLine remote service.
     *
     * @return the OrderLine remote service
     */
    public OrderLineService getOrderLineService() {
        return orderLineService;
    }

    /**
     * Sets the OrderLine remote service.
     *
     * @param orderLineService the OrderLine remote service
     */
    public void setOrderLineService(OrderLineService orderLineService) {
        this.orderLineService = orderLineService;
    }

    /**
     * Gets the OrderLine persistence.
     *
     * @return the OrderLine persistence
     */
    public OrderLinePersistence getOrderLinePersistence() {
        return orderLinePersistence;
    }

    /**
     * Sets the OrderLine persistence.
     *
     * @param orderLinePersistence the OrderLine persistence
     */
    public void setOrderLinePersistence(
        OrderLinePersistence orderLinePersistence) {
        this.orderLinePersistence = orderLinePersistence;
    }

    /**
     * Gets the Promo local service.
     *
     * @return the Promo local service
     */
    public PromoLocalService getPromoLocalService() {
        return promoLocalService;
    }

    /**
     * Sets the Promo local service.
     *
     * @param promoLocalService the Promo local service
     */
    public void setPromoLocalService(PromoLocalService promoLocalService) {
        this.promoLocalService = promoLocalService;
    }

    /**
     * Gets the Promo remote service.
     *
     * @return the Promo remote service
     */
    public PromoService getPromoService() {
        return promoService;
    }

    /**
     * Sets the Promo remote service.
     *
     * @param promoService the Promo remote service
     */
    public void setPromoService(PromoService promoService) {
        this.promoService = promoService;
    }

    /**
     * Gets the Promo persistence.
     *
     * @return the Promo persistence
     */
    public PromoPersistence getPromoPersistence() {
        return promoPersistence;
    }

    /**
     * Sets the Promo persistence.
     *
     * @param promoPersistence the Promo persistence
     */
    public void setPromoPersistence(PromoPersistence promoPersistence) {
        this.promoPersistence = promoPersistence;
    }

    /**
     * Gets the Vertical local service.
     *
     * @return the Vertical local service
     */
    public VerticalLocalService getVerticalLocalService() {
        return verticalLocalService;
    }

    /**
     * Sets the Vertical local service.
     *
     * @param verticalLocalService the Vertical local service
     */
    public void setVerticalLocalService(
        VerticalLocalService verticalLocalService) {
        this.verticalLocalService = verticalLocalService;
    }

    /**
     * Gets the Vertical remote service.
     *
     * @return the Vertical remote service
     */
    public VerticalService getVerticalService() {
        return verticalService;
    }

    /**
     * Sets the Vertical remote service.
     *
     * @param verticalService the Vertical remote service
     */
    public void setVerticalService(VerticalService verticalService) {
        this.verticalService = verticalService;
    }

    /**
     * Gets the Vertical persistence.
     *
     * @return the Vertical persistence
     */
    public VerticalPersistence getVerticalPersistence() {
        return verticalPersistence;
    }

    /**
     * Sets the Vertical persistence.
     *
     * @param verticalPersistence the Vertical persistence
     */
    public void setVerticalPersistence(VerticalPersistence verticalPersistence) {
        this.verticalPersistence = verticalPersistence;
    }

    /**
     * Gets the DemoItem local service.
     *
     * @return the DemoItem local service
     */
    public DemoItemLocalService getDemoItemLocalService() {
        return demoItemLocalService;
    }

    /**
     * Sets the DemoItem local service.
     *
     * @param demoItemLocalService the DemoItem local service
     */
    public void setDemoItemLocalService(
        DemoItemLocalService demoItemLocalService) {
        this.demoItemLocalService = demoItemLocalService;
    }

    /**
     * Gets the DemoItem remote service.
     *
     * @return the DemoItem remote service
     */
    public DemoItemService getDemoItemService() {
        return demoItemService;
    }

    /**
     * Sets the DemoItem remote service.
     *
     * @param demoItemService the DemoItem remote service
     */
    public void setDemoItemService(DemoItemService demoItemService) {
        this.demoItemService = demoItemService;
    }

    /**
     * Gets the DemoItem persistence.
     *
     * @return the DemoItem persistence
     */
    public DemoItemPersistence getDemoItemPersistence() {
        return demoItemPersistence;
    }

    /**
     * Sets the DemoItem persistence.
     *
     * @param demoItemPersistence the DemoItem persistence
     */
    public void setDemoItemPersistence(DemoItemPersistence demoItemPersistence) {
        this.demoItemPersistence = demoItemPersistence;
    }

    /**
     * Gets the Localization local service.
     *
     * @return the Localization local service
     */
    public LocalizationLocalService getLocalizationLocalService() {
        return localizationLocalService;
    }

    /**
     * Sets the Localization local service.
     *
     * @param localizationLocalService the Localization local service
     */
    public void setLocalizationLocalService(
        LocalizationLocalService localizationLocalService) {
        this.localizationLocalService = localizationLocalService;
    }

    /**
     * Gets the Localization remote service.
     *
     * @return the Localization remote service
     */
    public LocalizationService getLocalizationService() {
        return localizationService;
    }

    /**
     * Sets the Localization remote service.
     *
     * @param localizationService the Localization remote service
     */
    public void setLocalizationService(LocalizationService localizationService) {
        this.localizationService = localizationService;
    }

    /**
     * Gets the Localization persistence.
     *
     * @return the Localization persistence
     */
    public LocalizationPersistence getLocalizationPersistence() {
        return localizationPersistence;
    }

    /**
     * Sets the Localization persistence.
     *
     * @param localizationPersistence the Localization persistence
     */
    public void setLocalizationPersistence(
        LocalizationPersistence localizationPersistence) {
        this.localizationPersistence = localizationPersistence;
    }

    /**
     * Gets the Country local service.
     *
     * @return the Country local service
     */
    public CountryLocalService getCountryLocalService() {
        return countryLocalService;
    }

    /**
     * Sets the Country local service.
     *
     * @param countryLocalService the Country local service
     */
    public void setCountryLocalService(CountryLocalService countryLocalService) {
        this.countryLocalService = countryLocalService;
    }

    /**
     * Gets the Country remote service.
     *
     * @return the Country remote service
     */
    public CountryService getCountryService() {
        return countryService;
    }

    /**
     * Sets the Country remote service.
     *
     * @param countryService the Country remote service
     */
    public void setCountryService(CountryService countryService) {
        this.countryService = countryService;
    }

    /**
     * Gets the Country persistence.
     *
     * @return the Country persistence
     */
    public CountryPersistence getCountryPersistence() {
        return countryPersistence;
    }

    /**
     * Sets the Country persistence.
     *
     * @param countryPersistence the Country persistence
     */
    public void setCountryPersistence(CountryPersistence countryPersistence) {
        this.countryPersistence = countryPersistence;
    }

    /**
     * Gets the EcOrderIdSequence local service.
     *
     * @return the EcOrderIdSequence local service
     */
    public EcOrderIdSequenceLocalService getEcOrderIdSequenceLocalService() {
        return ecOrderIdSequenceLocalService;
    }

    /**
     * Sets the EcOrderIdSequence local service.
     *
     * @param ecOrderIdSequenceLocalService the EcOrderIdSequence local service
     */
    public void setEcOrderIdSequenceLocalService(
        EcOrderIdSequenceLocalService ecOrderIdSequenceLocalService) {
        this.ecOrderIdSequenceLocalService = ecOrderIdSequenceLocalService;
    }

    /**
     * Gets the EcOrderIdSequence remote service.
     *
     * @return the EcOrderIdSequence remote service
     */
    public EcOrderIdSequenceService getEcOrderIdSequenceService() {
        return ecOrderIdSequenceService;
    }

    /**
     * Sets the EcOrderIdSequence remote service.
     *
     * @param ecOrderIdSequenceService the EcOrderIdSequence remote service
     */
    public void setEcOrderIdSequenceService(
        EcOrderIdSequenceService ecOrderIdSequenceService) {
        this.ecOrderIdSequenceService = ecOrderIdSequenceService;
    }

    /**
     * Gets the EcOrderIdSequence persistence.
     *
     * @return the EcOrderIdSequence persistence
     */
    public EcOrderIdSequencePersistence getEcOrderIdSequencePersistence() {
        return ecOrderIdSequencePersistence;
    }

    /**
     * Sets the EcOrderIdSequence persistence.
     *
     * @param ecOrderIdSequencePersistence the EcOrderIdSequence persistence
     */
    public void setEcOrderIdSequencePersistence(
        EcOrderIdSequencePersistence ecOrderIdSequencePersistence) {
        this.ecOrderIdSequencePersistence = ecOrderIdSequencePersistence;
    }

    /**
     * Gets the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Gets the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Gets the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Gets the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Gets the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Gets the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Gets the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query to perform
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = addressPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
